# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # <-- เปลี่ยนจาก self-hosted

    # ให้ CI มี MongoDB ใช้เอง (ไม่ต้องพึ่ง Atlas)
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      # ถ้าต้องการใช้ Atlas ให้เปลี่ยนบรรทัดนี้เป็น:
      # MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_URI: mongodb://127.0.0.1:27017/petclinic_test?directConnection=true
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: |
            backend/yarn.lock
            frontend/yarn.lock

      # --- Backend ---
      - name: Install backend deps
        working-directory: backend
        run: yarn install --frozen-lockfile

      - name: Lint backend (optional)
        working-directory: backend
        run: yarn lint || echo "skip lint"

      - name: Test backend (optional)
        working-directory: backend
        run: yarn test || echo "skip tests"

      # --- Frontend ---
      - name: Install frontend deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Build frontend
        working-directory: frontend
        run: yarn build
        env:
          CI: false   # กันเคส CRA ทำ warning = error
