name: CI

on:
  push:
    branches:
      - main
      - '**'               
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:         

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      # 1) checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) setup node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      # 3) install backend deps
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # 4) run backend tests
      - name: Run Backend Tests
        working-directory: ./backend
        env:
          NODE_ENV: test
        run: npm test

  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
