name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          frontend/package-lock.json

    # Install backend dependencies
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm ci

    # Install frontend dependencies
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci

    # Build frontend
    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    # Run backend tests
    - name: Run Backend Tests
      working-directory: ./backend
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      run: npm test
